### ISSUE TITLE
About the Experimental Setup

### ISSUE THREAD

**Issue by haohaodw** [DAMO-NLP-SG/VCD#15]
I am very interested in your excellent work. I have some questions about the experiments. What temperature were the Regular and VCD in Table 1 and Table 2 tested? Looking forward to your reply !

**Comment by LengSicong** [comment]
We apply direct sampling without any temp normalization in our main experiments. For more ablations on decoding strategies, please refer to B.4. Effect of Different Sampling Strategies in the Appendix.

**Comment by haohaodw** [comment]
Thanks for your reply. When we use the default parameter settings in the code experiments/eval/object_hallucination_vqa_llava.py, does this mean that vcd is performing direct decoding? Is this default parameter setting consistent with the settings of the main experiment in the paper?

**Comment by LengSicong** [comment]
yes, it is doing direct sampling.

**Comment by haohaodw** [comment]
Thanks for your reply. How to use VCD in greedy search? What code do I need to modify?
