### ISSUE TITLE
Request for Parameter and Prompt Configurations Used in Table 3

### ISSUE THREAD

**Issue by ShanWang-Shan** [DAMO-NLP-SG/VCD#20]
I am writing to inquire about the parameters and prompts used in Table 3. Could you kindly share the configurations and prompts you applied for open-ended generation across each model?

**Comment by ShanWang-Shan** [comment]
I would also like to ask for the Hugging Face link for the specific version of Qwen-VL that you used.

**Comment by LengSicong** [comment]
The decoding strategy is also direct sampling without any normalization. The prompt is provided in Tab.11 in Appendix, following previous works. 

We adopt the first version of [QwenVL](https://huggingface.co/Qwen/Qwen-VL) that is available at that time.

**Comment by ShanWang-Shan** [comment]
Thank you very much for your response.
