### ISSUE TITLE
model_kwargs_cd  and model_kwargs problem

### ISSUE THREAD

**Issue by Mr-xiu** [DAMO-NLP-SG/VCD#7]
great work!
But I found that model_kwargs_cd is copied from model_kwargs every time in the sample method.
Is there some problem? Thanks!

**Comment by Stevetich** [comment]
I have the same question. I have noticed that the original and distorted image inputs have the same past_key_values setting. I wonder if the past_key_values should be set differently?

**Comment by frankRenlf** [comment]
I think it does not matter.
 you can find the process in llava_arch.py -> prepare_inputs_labels_for_multimodal

**Comment by LengSicong** [comment]
Hi all, thanks for your interest and valuable discussions. 

We are sorry for this problem we made while cleaning the open-source codes. 

For the solution and more discussions, please refer to [issue#13](https://github.com/DAMO-NLP-SG/VCD/issues/13).
