### ISSUE TITLE
unable to reproducing the results of llava

### ISSUE THREAD

**Issue by frankRenlf** [DAMO-NLP-SG/VCD#9]
I've followed the process, but I'm three points under. What other details do I need to pay attention to in order to reproduce the results of the paper?

**Comment by LengSicong** [comment]
Hi, may I know more details about your experiments so that we can help you better?

**Comment by LengSicong** [comment]
The fluctuating may come from the random sampling process, depending on the sampling strategies. Moreover, the process of adding random gaussian noise may also introduce randomness. 

For the regular decoding, are u using a newer version of LLaVA?

**Comment by frankRenlf** [comment]
thx for your reply. Yes, I just use llava7b.
<img width="126" alt="image" src="https://github.com/DAMO-NLP-SG/VCD/assets/89248496/0bce6c8e-04dc-4c7d-83ad-6409cec74df7">
And I want to know how's the std comes from.

**Comment by LengSicong** [comment]
Hi, the decoding strategy for the main table is always direct sampling without any constraints (i.e., top p, temperature normalization). The std may come from the sampling process or the randomness while adding the Gaussian noise to obtain a noised image.

**Comment by frankRenlf** [comment]
Hi, but for regular, it also has std in results, what causes this? When I set seed, the results will not change. So the std may come from sampling process and the difference is got by difference seeds?
<img width="199" alt="image" src="https://github.com/DAMO-NLP-SG/VCD/assets/89248496/aac32373-827b-4f72-9a34-bffcd4f2255e">

**Comment by LengSicong** [comment]
Yep, correct. When the seed is different, the sampling process during decoding and the process of adding Gaussian noises to the original image would both introduce randomness that may cause the std.

**Comment by haohaodw** [comment]
Hi, I still don't know which version of llava to use to reproduce the results. Can you share the link of Huggingface?

**Comment by LengSicong** [comment]
https://huggingface.co/liuhaotian/llava-v1.5-7b

**Comment by HaozheZhao** [comment]
> https://huggingface.co/liuhaotian/llava-v1.5-7b

Hi, Sicong, I have a problem that why the result report in the paper is much lower than the performance report in the original LLAVA 1.5 paper? 

For example, in the orginal LLAVA-1.5 paper, it report the POPE F1 score in three split( Ran, Adv and Pop): 87.3 86.1 84.2 

But in your paper, the result is 81.33, 77.57 and 80.06.

**Comment by wzczc** [comment]
> > https://huggingface.co/liuhaotian/llava-v1.5-7b
> 
> Hi, Sicong, I have a problem that why the result report in the paper is much lower than the performance report in the original LLAVA 1.5 paper?
> 
> For example, in the orginal LLAVA-1.5 paper, it report the POPE F1 score in three split( Ran, Adv and Pop): 87.3 86.1 84.2
> 
> But in your paper, the result is 81.33, 77.57 and 80.06.

@HaozheZhao Hi, I have the same question. Have you figured it out?
